### ISSUE TITLE
Item missing from trunk and glovebox randomly

### ISSUE THREAD

**Issue by Enos1316** [dutchplayers/FiveM-Resources#119]
After server restart item that are stored in trunk and glovebox got disappeared. I am using drp_garage.

**Comment by TristGit** [comment]
![image](https://user-images.githubusercontent.com/57966174/86240229-a39fe200-bb55-11ea-9a85-8c5b7322a14d.png)
This occurs when opening a vehicle that nobody owns, a world vehicle. Also an unrelated side note; even with the ownership set to true, you can still open most vehicles - but you dont seem to be able to open trucks for some odd reason. I've since disabled it to false but havent tried yet.

But this error basically seems like its attempting to create another SQL data entry when it is opened. 
Is this normal/inconsequential? Is there a way to disable the console?

**Comment by shox92** [comment]
Hey check theese Line in esx_trunk-sv.lua

AddEventHandler(
  "onMySQLReady",
  function()
    --MySQL.Async.execute("DELETE FROM `trunk_inventory` WHERE `owned` = 0", {})
  end
)

**Comment by Enos1316** [comment]
Thanks bro after changing this no one in my server reports the issue
