### ISSUE TITLE
Can't use weapons given by admin

### ISSUE THREAD

**Issue by donnayy** [dutchplayers/FiveM-Resources#189]
Hello how are you? 
when I try to give myself an weapon, it appear on my inventory but i can't equip it! 
i need to go to the weaponshop from inventoryhud to be able to use a gun, and this happends in policejob as well when I try to get guns from armory.

**Comment by ShyKaZa** [comment]
Well for that exist a simple answer. This inventory in v3 dont use default weapons anymore only " weapons as items" and when you know this Policejob armory works as "spawner for default weapons" thats why there is included weaponshop for police in inventory.

This is because when you use default weapons "without being an item" you can dupe them everywhere. So basicly its not a bug its function.

**Comment by donnayy** [comment]
Thank you for the fast reply!
is any version working with the deafult weapons? 
I downloaded one but it was bugged with double money and i couldn't give money.
I'm currently using the version 3.1 wich is pretty fine with those "troubles"

Is the v2 still playable?

**Comment by ShyKaZa** [comment]
You can ofc use v2 2.4 ita working fine..

Dňa pi 23. 10. 2020, 17:13 donnay <notifications@github.com> napísal(a):

**Comment by donnayy** [comment]
thank you!
