### ISSUE TITLE
SCRIPT ERROR: @esx_inventoryhud_trunk/server/esx_trunk-sv.lua:151: attempt to call a nil value (field 'canCarryItem')

### ISSUE THREAD

**Issue by Evilcho0TM** [dutchplayers/FiveM-Resources#71]
Hello, I have problem can anyone help me with this problem , when i put the drugs in trunk and try to take send me this : SCRIPT ERROR: @esx_inventoryhud_trunk/server/esx_trunk-sv.lua:151: attempt to call a nil value (field 'canCarryItem')

But when I put money and weapons everything is okey????

**Comment by BrutalBirdie** [comment]
I think you need to provide better context.
Which drugs resource you are using? esx_drugs original, from dutchplayers, esx_illigal_drugs?

This is the line in the code that creates the error.

https://github.com/dutchplayers/esx-inventoryhud/blob/f3a0422b514dd8d33a4ec9947d4d1f5f0876cf7e/esx_inventoryhud_trunk/server/esx_trunk-sv.lua#L151

Official es_extended doc
[xPlayer.canCarryItem Doc](https://esx-org.github.io/es_extended/server/xplayer/functions/cancarryitem/#xplayercancarryitem)

The issue can really be only 2 things `item` or `count` is nil.

Also your database scheme could be interesting, if you are using an outdated database with `limit` instead of `weight` for items you would get the same error.

Edit:
If you want to debug this particular I would suggest printing `item` and `count` before line 151 aka. above the if statement.
If both return a value the next thing to check would be if xPlayer is actually present (note xPlayer is a table, for printing tables use: 
```
print(ESX.DumpTable(xPlayer)
```
[ESX.DumpTable() Doc](https://esx-org.github.io/es_extended/common/functions/dumptable/)

**Comment by BrutalBirdie** [comment]
Since there is no feedback coming and I can tell from my Server using esx_drugs and esx_illigal_drugs with no problems that this is a user issue, and this issue can be closed for now.
