### ISSUE TITLE
Cannot buy weapon

### ISSUE THREAD

**Issue by Rado236** [dutchplayers/FiveM-Resources#82]
I got my firearms license but I cannot buy any weapon.
![20200510023549_1](https://user-images.githubusercontent.com/55925335/81488300-bee62380-926f-11ea-894a-75dec97149ed.jpg)

**Comment by FiveEYZ** [comment]
can u check in the database `user_licenses` if u have a license entry there with type of "weapon"

**Comment by Rado236** [comment]
Yes, I have

**Comment by FiveEYZ** [comment]
u using latest ESX 1.2?

**Comment by Rado236** [comment]
Yes

**Comment by RuisSoftware** [comment]
It's not related to inventoryhud since you edited es_extended or using an unsupported version. There is no 3D text in inventoryhud.

It should look like: https://camo.githubusercontent.com/93de7e4126251477d5132c3a864fe405588a7c07/68747470733a2f2f692e6779617a6f2e636f6d2f34313135336131313839636132383439313433336163653633343336313361342e706e67
